config/routes.rb
CoordinadorAlpes::Application.routes.draw do
  get "dashboard/dashboard"
  get "planeacion/resultados"
  get "materia/detalles"
  post "materia/listafiltrada"
  get "materia/infomateria"
  get "estudiante/infoestudiante"
  post "estudiante/listafiltrada"
  get "generar_secciones/generar"
  post "generar_secciones/generarSecciones"

  get "materia/cupos"
  get "estudiante/cuposmas8"
  get "welcome/index"
  get "reservas/ultimosEstudiantes"
  get "reservas/reservasUltimosEst"
  get "reservas/limpiarEscenario"
  get "reservas/home"
  get "reservas/planearSemestres"
  get "reservas/semestrePlaneado"
  get "reservas/detalles"

  get "estudiante/buscarEstudiantesMasOcho"
  post "estudiante/creditosfaltantes"

  get "estado_carpeta/estadoCarpeta"
  get "estado_carpeta/carpeta"
  get "estudiante/result"
  get "materia/new"
  get "estudiante/new"
  get "users/new"

  get "estado_carpeta/home"
  post "estado_carpeta/estadoCarpeta"
  post "reservas/setMateriasSemestre"

  root 'welcome#index'

  

end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController

  #Contiene la lista de materias de los 4 semestres
  @@materiasSemestres=Array.new(4)

  def materiasVistas(idEstudiante)
    materiasV=[]
    carpetas=Carpeta.where("codigoMateria is NOT NULL AND idEstudiante=?",idEstudiante)
    carpetas.each do |c|
      materiasV.push(c.codigoMateria)
    end
    
    registros= Registro.where("idEstudiante=?", idEstudiante)
    if(!registros.empty?)
      registros.each do |r|
          plans=Planeacion.find(r.idPlaneacion)
        materia= Materia.find(plans.codigoMateria)
        materiasV.push(materia.codigo)
      end
    end
    materiasV= materiasV.uniq
    puts "acaACaw"
    return materiasV
    
  end

  def ultimosEstudiantes
    @ultimosSem=[]
    creditosFal = Carpeta.select("sum(creditos) as numCred, idEstudiante").where(codigoMateria:nil).group("idEstudiante");
    @totalCred=0
    creditosFal.each do |est|
      if(est.numCred<=8)
        @ultimosSem.push(Estudiante.find(est.idEstudiante))
        @totalCred+=est.numCred
      end
    end

  end

  def darEstUltimosSem(carpetas)
    ultimosSem=[]
    creditosFal = carpetas.select("sum(creditos) as numCred, idEstudiante").where(codigoMateria:nil).group("idEstudiante");

    creditosFal.each do |est|
      if(est.numCred<=8)
        ultimosSem.push(Estudiante.find(est.idEstudiante))
      end
    end
    return ultimosSem
  end

  def reservasUltimosEst
    carpetas=Carpeta.all
    ultimosSem=darEstUltimosSem(carpetas)
    @materias=[]
    ultimosSem.each do |est|

      #Para cada estudiante,definir cada tipo de materia que le falta y el número de cŕeditos
      faltantes=darTiposFaltantes(carpetas, est.id)
      if(!faltantes.empty?)
          #Para cada tipo que le falta, buscar la lista de materias faltantes de ese tipo
           faltantes.each do |tipofalt|

             materiasSem1=@@materiasSemestres[0]
             if(materiasSem1==nil)
               materiasSem1=Materia.all
             end
             materiasPosibles=materiasSem1.select{
               |mat| mat.tipo==tipofalt.tipoMateria
             }
                 #materiasPosibles= Materia.where("tipo=?", tipofalt.tipoMateria)
             materiasVistas=materiasVistas(est.id)
             materiasPosibles=materiasPosibles.delete_if{|m| materiasVistas.include?(m.codigo)}

             if(!materiasPosibles.empty?)
               if(tipofalt.numCreFaltantes<=4)
                 #Es solo una materia(Asumiendo materias de 4 créditos)

                 randMat=Random.rand(materiasPosibles.size)
                 materia=materiasPosibles[randMat]
                 #Agregar el cupo
                 prioridad="Ultimo Semestre " << est.programa
                 agregarAPlaneacion(materia.id,prioridad,"1",est.id)
               else
                 #Le faltan dos materias

                 n= (tipofalt.numCreFaltantes/4).round

                 randMat1=Random.rand(materiasPosibles.size)
                 randMat2=Random.rand(materiasPosibles.size)
                 while(randMat1==randMat2)
                   randMat2=Random.rand(materiasPosibles.size)
                 end
                 materia=materiasPosibles[randMat1]
                 #Agregar el cupo
                 prioridad="Ultimo Semestre " << est.programa
                 agregarAPlaneacion(materia.id, prioridad,"1",est.id)

                 materia=materiasPosibles[randMat2]
                 #Agregar el cupo
                 prioridad="Ultimo Semestre " << est.programa
                 agregarAPlaneacion(materia.id,prioridad,"1",est.id)
               end
             end
           end
      end

    end
    @materias=Materia.all

  end

  # Inicio métodos para calcular los otros cupos
  #ARREGLARRRRRR!!!!!!!!!!!!!!!!!!!!!!!!!!!
  def cuposmas8

    @algunos = []
    todos = Estudiante.all
    todos.each do |estudiante|
      id = estudiante.id

      faltantes=Carpeta.select("tipoMateria, sum(creditos) as numCreFaltantes").where("idEstudiante=? AND codigoMateria IS NULL",(id)).group("tipoMateria")
      creditosFal = 0
      faltantes.each do |fal|
        creditosFal += fal.numCreFaltantes
      end

      #creditosFal = (Carpeta.where(idEstudiante: id , codigoMateria: nil , creditos: 4).size)*4
      if(creditosFal>8)
        #e = [ estudiante.id , estudiante.nombre , estudiante.apellido , estudiante.codigo , estudiante.programa , creditosFal ]
        #@algunos << e
        i = 0
        faltantes.each do |tipofalt|

          materiasSem1=@@materiasSemestres[0]
          if(materiasSem1==nil)
            materiasSem1=Materia.all
          end
          materiasPosibles=materiasSem1.select{
              |mat| mat.tipo==tipofalt.tipoMateria
          }

          #materiasPosibles= Materia.where("tipo=?", tipofalt.tipoMateria)
          puts "Antes"
          materiasVistas=materiasVistas(estudiante.id)
          puts "aca22"
          materiasPosibles=materiasPosibles.delete_if{|m| materiasVistas.include?(m.codigo)}
puts "Llego aca2"
          if(!materiasPosibles.empty?)
            if(tipofalt.numCreFaltantes<=4)
              #Es solo una materia(Asumiendo materias de 4 créditos)
              if(i<2)
                randMat=Random.rand(materiasPosibles.length)
                materia=materiasPosibles[randMat]

                #materia.cupo+=1
                #materia.save
                prioridad=darPrioridad(materia,estudiante)
                agregarAPlaneacion(materia.id,prioridad,"1",id)


                i += 1
              end
            else
              #Le faltan dos materias
puts "Llego aca3"
              n= (tipofalt.numCreFaltantes/4).round
              randMat1=Random.rand(materiasPosibles.size)
              randMat2=Random.rand(materiasPosibles.size)
              
              if(i<2)
                
                materia=materiasPosibles[randMat1]
                #materia.cupo+=1
                #materia.save
                prioridad=darPrioridad(materia,estudiante)
                agregarAPlaneacion(materia.id,prioridad,"1",id)
                i += 1
              end
puts "Llego aca3"
              if(materiasPosibles.size!=1)
                while(randMat1==randMat2)
                  randMat2=Random.rand(materiasPosibles.size)
                end
      
              
                if(i<2)
                  puts "5"
                  materia=materiasPosibles[randMat2]
                  #materia.cupo+=1
                  #materia.save
                  prioridad=darPrioridad(materia,estudiante)
                  agregarAPlaneacion(materia.id,prioridad,"1",id)
                  i += 1
                end
              end
            end
          end
        end
      end
    end
    @materias =  Materia.all
  end

  def darPrioridad(materia,estudiante)
    prioridad=""
    if(estudiante.programa==materia.programa)
      prioridad="Mismo programa"
    else
      prioridad=estudiante.programa
    end
    return prioridad
  end

  def darTiposFaltantes(carpetas, id)
    faltantes=[]
    faltantes=carpetas.select("tipoMateria, sum(creditos) as numCreFaltantes").where("idEstudiante=? AND codigoMateria IS NULL",(id)).group("tipoMateria")
    return faltantes
  end

  def agregarAPlaneacion(materia,prioridad,semestre,estudiante)
    planeaciones=Planeacion.all
    planeacionesMateria=planeaciones.where("codigoMateria=? AND semestre=?",(materia),(semestre))
    if(planeacionesMateria.empty?)
      #Toca crearlo
      p=Planeacion.create(codigoMateria: materia, cupos: 1, semestre: semestre)
      p.save
      Registro.create(idEstudiante: estudiante, idPlaneacion: p.id, prioridad: prioridad)
    else
      planeado=planeacionesMateria[0]
      planeado.cupos+=1;
      planeado.save
      Registro.create(idEstudiante: estudiante, idPlaneacion: planeado.id, prioridad: prioridad)
    end

  end

  def darEstUltimosYNoUltSem( semestre)

    ultimosSem=[]
    noUltimoSem=[]
    creditosFal = Carpeta.select("sum(creditos) as numCred, idEstudiante").where(codigoMateria:nil).group("idEstudiante");
    creditosFal.each do |est|
      registros=Registro.where(idEstudiante:est.idEstudiante)
      numRegistroSem=0
      registros.each do |reg|
        plans=Planeacion.find(reg.idPlaneacion)
        if(plans.semestre<semestre)
          numRegistroSem+=1
        end
      end

      #Asumiendo materias de 4 créditos
      credFaltantes=est.numCred-numRegistroSem*4;
      if(credFaltantes<=8 and credFaltantes>0)
        ultimosSem.push(Estudiante.find(est.idEstudiante))
        puts "Ultimo semestre"
        puts est.idEstudiante
      elsif (credFaltantes>8)
        noUltimoSem.push(Estudiante.find(est.idEstudiante))
        puts "No Ultimo semestre"
        puts est.idEstudiante
      end
    end
    return ultimosSem, noUltimoSem
  end

  def darTiposFaltantesSem( id, semestre)
    faltantes=[]
    faltantes=Carpeta.select("tipoMateria, sum(creditos) as numCreFaltantes").where("idEstudiante=? AND codigoMateria IS NULL",(id)).group("tipoMateria")

    registros=Registro.where(idEstudiante:id)
    numRegistroSem=0
    registros.each do |reg|
      plans=Planeacion.find(reg.idPlaneacion)
      if(plans.semestre<semestre)
        mat=Materia.find(plans.codigoMateria)
        faltantes.detect{|f|
          if(f.tipoMateria == mat.tipo)
            f.numCreFaltantes= f.numCreFaltantes-4
          end
        }
      end
    end
    faltantes= faltantes.delete_if{|f| f.numCreFaltantes==0}
    return faltantes
  end


  def limpiarEscenario
    Planeacion.delete_all
    Registro.delete_all
    render 'detalles' 
  end

def reservasSemestrePorEstUltimo(semestre)

    ultimosSem,noUltimoSem=darEstUltimosYNoUltSem(semestre)
    @materias=[]
    ultimosSem.each do |est|

      #Para cada estudiante,definir cada tipo de materia que le falta y el número de cŕeditos
      faltantes=darTiposFaltantesSem( est.id, semestre)
      if(!faltantes.empty?)

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/reservas/home.html.erb
<script>
    function doload() {
        var checkboxs=document.getElementsByName("materias1[]");
        var okay=false;
        for(var i=0,l=checkboxs.length;i<l;i++)
        {
            if(checkboxs[i].checked)
            {
                okay=true;
            }
        }
        if(okay)alert("Thank you for checking a checkbox");
        else alert("Please check a checkbox");
    }
    
    function doload2() {
      var checkboxs=document.getElementsByName("rep");
      for(var i=0,l=checkboxs.length;i<l;i++)
      {
          if(checkboxs[i].checked)
          {
              var val=checkboxs[i].value
              var checkboxsCam=document.getElementsByName("materias"+val+"[]");
              var checkboxsOr=document.getElementsByName("materias1[]");
                  for(var j=0,m=checkboxsOr.length;j<m;j++)
                  {
                      if(checkboxsOr[j].checked){
                          checkboxsCam[j].checked=true;
                      }
                  }
          }

      }

      var modalLink2 = document.getElementById('linkSem2'); 
      var modalLink3 = document.getElementById('linkSem3'); 
      var modalLink4 = document.getElementById('linkSem4');

      if(checkboxs[0].checked){
        //Dos está seleccionado
        if(checkboxs[1].checked){
          //Tres está seleccionadp

          if(checkboxs[2].checked){
            alert("Please check a checkbox");
            //2,3, 4 selecionados. Ir al final.

            document.getElementById("setMaterias").submit();
            modalLink2.href='/';
          }else{
            //2,3 selecionados. Ir a 4
            modalLink2.href='#sem4';

          }
        }else{
          
        //2 seleccionado. Ir a tres
         modalLink2.href='#sem3';
          if(checkboxs[2].checked){
            //2, 4 selecionados. El link3 ejecuta el form
            modalLink4.onclick=function () {  document.getElementById("setMaterias").submit(); };
            modalLink4.href='/';
          }else{
            //Solo 2 seleccionado
            //Muestra la opción de replicar en 3
            document.getElementById("replicar3").style.display='block';
          }
        }
      }
      else if(checkboxs[1].checked){
        //3 seleccionado
          if(checkboxs[2].checked){
            //3, 4 selecionados. El link2 ejecuta el form
            modalLink3.onclick=function () {  document.getElementById("setMaterias").submit(); };
            modalLink3.href='/';
          }else{
            //Solo 3 seleccionado
            var d = document.getElementById('replicar2');

            var olddiv = document.getElementById('rep32');

            d.removeChild(olddiv);
            d.removeChild(document.getElementById('rep32s'));
            modalLink3.href='#sem4';
            document.getElementById("replicar2").style.display='block';
            
          } 
      }else if(checkboxs[2].checked){
        //4 seleccionado
              var d = document.getElementById('replicar2');

              var olddiv = document.getElementById('rep32');

              d.removeChild(olddiv);
              d.removeChild(document.getElementById('rep32s'));
              document.getElementById("replicar2").style.display='block';
        modalLink4.onclick=function () {  document.getElementById("setMaterias").submit(); };
        modalLink4.href='/';
      }
      else if(!checkboxs[0].checked && !checkboxs[1].checked && !checkboxs[2].checked){
        document.getElementById("replicar2").style.display='block';
      } 
    }

function doload3() {
      var checkboxs=document.getElementsByName("rep2");
      for(var i=0,l=checkboxs.length;i<l;i++)
      {
         if(checkboxs[i].checked)
          {
              var val=checkboxs[i].value
              var checkboxsCam=document.getElementsByName("materias"+val+"[]");
              var checkboxsOr=document.getElementsByName("materias2[]");
                  for(var j=0,m=checkboxsOr.length;j<m;j++)
                  {
                      if(checkboxsOr[j].checked){
                          checkboxsCam[j].checked=true;
                      }
                  }
          }

      }

      var modalLink3 = document.getElementById('linkSem3'); 
      var modalLink4 = document.getElementById('linkSem4');

      if(checkboxs.length==2){
        if(checkboxs[0].checked){

          //tres está seleccionado
          if(checkboxs[1].checked){
            //3,4 está seleccionado
            document.getElementById("setMaterias").submit(); 
          }else{
          //3 seleccionado. Ir a 4
           modalLink3.href='#sem4';

          }
        }
        else if(checkboxs[1].checked){

          //4 está seleccionado
          s=modalLink3.href
          if(s.indexOf("#sem4") !== -1){
            //3 Ya ha sido replicado
            document.getElementById("setMaterias").submit();
          }else{
            modalLink3.href=='#sem3';
          }
        }
      }else if(checkboxs.length==1){
        if(checkboxs[0].checked){

          //4 está seleccionado
          s=modalLink3.href
          if(s.indexOf("#sem4") !== -1){
            //3 Ya ha sido replicado
            document.getElementById("setMaterias").submit();
          }else{
            modalLink3.href=='#sem3';
          }
        }

                
      }
    }


function doload4() {
      var checkboxs=document.getElementsByName("rep3");
      for(var i=0,l=checkboxs.length;i<l;i++)
      {
         if(checkboxs[i].checked)
          {
              var val=checkboxs[i].value
              var checkboxsCam=document.getElementsByName("materias"+val+"[]");
              var checkboxsOr=document.getElementsByName("materias2[]");
                  for(var j=0,m=checkboxsOr.length;j<m;j++)
                  {
                      if(checkboxsOr[j].checked){
                          checkboxsCam[j].checked=true;
                      }
                  }
          }

      }

      var modalLink3 = document.getElementById('linkSem3'); 
      var modalLink4 = document.getElementById('linkSem4');

      if(checkboxs.length==2){
        if(checkboxs[0].checked){

          //tres está seleccionado
          if(checkboxs[1].checked){
            //3,4 está seleccionado
            document.getElementById("setMaterias").submit(); 
          }else{
          //3 seleccionado. Ir a 4
           modalLink3.href='#sem4';

          }
        }
        else if(checkboxs[1].checked){

          //4 está seleccionado
          s=modalLink3.href
          if(s.indexOf("#sem4") !== -1){
            //3 Ya ha sido replicado
            document.getElementById("setMaterias").submit();
          }else{
            modalLink3.href=='#sem3';
          }
        }
      }else if(checkboxs.length==1){
        if(checkboxs[0].checked){

          //4 está seleccionado
          s=modalLink3.href
          if(s.indexOf("#sem4") !== -1){
            //3 Ya ha sido replicado
            document.getElementById("setMaterias").submit();
          }else{
            modalLink3.href=='#sem3';
          }
        }

                
      }
    }
 function checkAll(number){
  var checkboxs=document.getElementsByName("materias"+number+"[]");

  for(var i=0,l=checkboxs.length;i<l;i++)
  {
        checkboxs[i].checked=true;
  }
 }

 function verificarAlguna(number){
  var checkboxs=document.getElementsByName("materias"+number+"[]");
  var okay=false;
  for(var i=0,l=checkboxs.length;i<l;i++)
  {
    if(checkboxs[i].checked)
      {
          okay=true;
      }
  }
  if(!okay){
    alert("Error! Debe seleccionar alguna");
  }
 }
</script>

<h1>Estudiantes de último semestre</h1>
<h1>Estudiantes de último semestre</h1>
<p>Ver estudiantes de último semestre</p>
<%= form_tag('ultimosEstudiantes',:method => :get) do%>
    <%= submit_tag("Ver") %>
<% end%>



 
 <p>Planear Proximos Semestres</p>
<%= form_tag('planearSemestres',:method => :get) do%>
<%= submit_tag("Planear Semestres") %>
<% end %>

<%= form_tag(generar_secciones_generar_path,:method => :get) do%>
<%= submit_tag("Generar Secciones") %>
<% end %>

 <p>Ver Planeacion proximos semestres </p>
<%= form_tag('semestrePlaneado',:method => :get) do%>
<input hidden name="semestre" value="1">
<%= submit_tag("Ver Cupos semestre 1") %>
<% end %>

<%= form_tag('semestrePlaneado',:method => :get) do%>
<input hidden name="semestre" value="2">
<%= submit_tag("Ver Cupos semestre 2") %>
<% end %>

<%= form_tag('semestrePlaneado',:method => :get) do%>
    <input hidden name="semestre" value="3">
    <%= submit_tag("Ver Cupos semestre 3") %>
<% end %>

<%= form_tag('semestrePlaneado',:method => :get) do%>
    <input hidden name="semestre" value="4">
    <%= submit_tag("Ver Cupos semestre 4") %>
<% end %>

<br><br>
 <p>Limpiar Escenario</p>
<%= form_tag('limpiarEscenario',:method => :get) do%>
<%= submit_tag("Limpiar") %>
<% end %>

<!-- Button to trigger modal -->
<a href="#myModal" role="button" class="btn" data-toggle="modal">Ejecutar planeacion</a>

<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <p>Desea especificar las materias en cada semestre?</p>
  </div>
  <div class="modal-footer">
    <%= form_tag('planearSemestres',:method => :get) do%>
      <%= submit_tag("No") %>
    <% end %>
    <a href="#sem1" data-toggle="modal" data-dismiss="modal" class="btn btn-primary">Si</a>
  </div>
</div>
<%= form_tag('setMateriasSemestre',:method => :get,:id => "setMaterias"  ) do%>
<div id="sem1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Planeacion Semestre 1</h3>
  </div>
  <div class="modal-body">
    <p>Planeacion Semestre 1</p>

        <input hidden name="materias1[]"/>
        <%@materias1 = Materia.all%>
        <%@materias1.each do |c|%>
            <%= check_box_tag "materias1[]", c.id, false, :id => "materias1_#{c.id}" %> <%= c.nombre%><br />
        <%end%>
        <p> Replicar en </p>
      <input id="rep2" name="rep" type="checkbox" value="2" /> 2<br />
      <input id="rep3" name="rep" type="checkbox" value="3" /> 3<br />
      <input id="rep4" name="rep" type="checkbox" value="4" /> 4<br />
    
  </div>
  <div class="modal-footer">
        <a href="#sem2" id="linkSem2" data-toggle="modal" data-dismiss="modal" class="btn btn-primary" onclick="doload2()">Siguiente1</a>
  </div>
</div>

<div id="sem2" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Planeacion Semestre 2</h3>
  </div>
  <div class="modal-body">
    <p>Materias del semestre 2</p>
    <input hidden name="materias2[]"/>
    <%@materias2 = Materia.all%>
    <%@materias2.each do |c|%>
        <%= check_box_tag "materias2[]", c.id, false, :id => "materias2_#{c.id}" %> <%= c.nombre%><br />
    <%end%>
    <div style="display:none" id="replicar2">
     <p> Replicar en </p>
      <input id="rep32" name="rep2" type="checkbox" value="3"> <div id="rep32s">3</div><br />
      <input id="rep42" name="rep2" type="checkbox" value="4" /> 4<br />
    </div>
  </div>

  <div class="modal-footer">

    <a href="#sem3" id="linkSem3" data-toggle="modal" data-dismiss="modal" class="btn btn-primary" onclick="doload3()">Siguiente2</a>
  </div>
</div>

<div id="sem3" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Planeacion Semestre 3</h3>
  </div>
  <div class="modal-body">
    <p>Materias del semestre 3</p>
    <input hidden  name="materias3[]"/>
        <%@materias3 =  Materia.all%>
        <%@materias3.each do |c|%>
            <%= check_box_tag "materias3[]", c.id, false, :id => "materias3_#{c.id}" %> <%= c.nombre%><br />
        <%end%>
  <div style="display:none" id="replicar3">
     <p> Replicar en </p>
      <input id="rep4" name="rep3" type="checkbox" value="4" /> 4<br />
    </div>
  </div>
  <div class="modal-footer">


    <a href="#sem4" id="linkSem4" data-toggle="modal" data-dismiss="modal" class="btn btn-primary">Siguiente3</a>
  </div>
</div>

<div id="sem4" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <p>Planeacion Semestre 4</p>
    <input hidden name="materias4[]"/>
        <%@materias4 = Materia.all%>
        <%@materias4.each do |c|%>
            <%= check_box_tag "materias4[]", c.id, false, :id => "materias4_#{c.id}" %> <%= c.nombre%><br />
        <%end%>
  </div>
  <div class="modal-footer">
    <%= submit_tag("Terminar") %>


  </div>
</div>
    <% end %>

app/views/reservas/reservasUltimosEst.html.erb
<h1>Reservas Cupos Ultimos Semestres</h1>
<br><br>

<div class="well">
<table>
  <tr>
	<th>id</th>
    <th>Nombre</th>
    <th>Tipo</th>
  </tr>
  <% n=0%>
  <% @materias.each do |mat| %>

      <tr>
	<td><%= mat.id %></td>
        <td><%= mat.nombre %></td>
        <td><%= mat.tipo %></td>
      </tr>

  <% end %>
</table>

</div>
<p> Número de cupos asignados= <%=n%></p>
<p>Limpiar Escenario</p>
<%= form_tag('limpiarEscenario',:method => :get) do%>
<%= submit_tag("Limpiar") %>
<% end %>
<p>Find me in app/views/reservas/reservasUltimosEst.html.erb</p>

app/views/reservas/ultimosEstudiantes.html.erb
<h1>Estudiantes de último semestre</h1>
<div class="well">
<table>
  <tr>
    <th>id</th>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Codigo</th>
    <th>Programa</th>
    <th>Creditos</th>
  </tr>
  <% @ultimosSem.each do |estudiante| %>

      <tr>
	<td><%= estudiante.id %></td>
        <td><%= estudiante.nombre %></td>
        <td><%= estudiante.apellido %></td>
        <td><%= estudiante.codigo %></td>
        <td><%= estudiante.programa %></td>

      </tr>

  <% end %>
</table>
</div>
<p> El número de materias que se estos estudiantes tiene que ver es: <%=@totalCred/4%> </p>