config/routes.rb
CoordinadorAlpes::Application.routes.draw do
  get "dashboard/dashboard"
  get "planeacion/resultados"
  get "materia/detalles"
  post "materia/listafiltrada"
  get "materia/infomateria"
  get "estudiante/infoestudiante"
  post "estudiante/listafiltrada"
  get "generar_secciones/generar"
  post "generar_secciones/generarSecciones"

  get "materia/cupos"
  get "estudiante/cuposmas8"
  get "welcome/index"
  get "reservas/ultimosEstudiantes"
  get "reservas/reservasUltimosEst"
  get "reservas/limpiarEscenario"
  get "reservas/home"
  get "reservas/planearSemestres"
  get "reservas/semestrePlaneado"
  get "reservas/detalles"

  get "estudiante/buscarEstudiantesMasOcho"
  post "estudiante/creditosfaltantes"

  get "estado_carpeta/estadoCarpeta"
  get "estado_carpeta/carpeta"
  get "estudiante/result"
  get "materia/new"
  get "estudiante/new"
  get "users/new"

  get "estado_carpeta/home"
  post "estado_carpeta/estadoCarpeta"
  post "reservas/setMateriasSemestre"

  root 'welcome#index'

  

end

app/models/materia.rb
class Materia < ActiveRecord::Base
end

app/controllers/materia_controller.rb
class MateriaController < ApplicationController
  def cupos
	
  end

 def new
	@materias = Materia.all
 end

def infomateria
	id= params[:id]
	@mate = Materia.find(id)

	#Info planeacion
	@plan1 = Planeacion.where(codigoMateria: id , semestre: "1")
	reg1 = Registro.where(idPlaneacion: @plan1)
	@p1ulti = reg1.where("prioridad like ? ", "%Ultimo%").count
	@p1mismo = reg1.where("prioridad like ? ", "%Mismo%").count

	@plan2 = Planeacion.where(codigoMateria: id , semestre: "2")
	reg2 = Registro.where(idPlaneacion: @plan2)
	@p2ulti = reg2.where("prioridad like ? ", "%Ultimo%").count
	@p2mismo = reg2.where("prioridad like ? ", "%Mismo%").count

	@plan3 = Planeacion.where(codigoMateria: id , semestre: "3")
	reg3 = Registro.where(idPlaneacion: @plan3)
	@p3ulti = reg3.where("prioridad like ? ", "%Ultimo%").count
	@p3mismo = reg3.where("prioridad like ? ", "%Mismo%").count

	@plan4 = Planeacion.where(codigoMateria: id , semestre: "4")
	reg4 = Registro.where(idPlaneacion: @plan4)
	@p4ulti = reg4.where("prioridad like ? ", "%Ultimo%").count
	@p4mismo = reg4.where("prioridad like ? ", "%Mismo%").count

end

def listafiltrada
	@m= params[:M]
	@materias = Materia.all
end

def detalles 
	id= params[:id]
	@sem= params[:sem]
	@materia = Materia.find(id)
	
	plan = Planeacion.where(codigoMateria: id, semestre: @sem)
	@reg = Registro.where(idPlaneacion: plan.first.id)

end 

end 

app/helpers/materia_helper.rb
module MateriaHelper
end

app/views/materia/cupos.html.erb
<h1>Cupos de Materias</h1>


<div class="well">
<table>
  <tr>
    <th>id</th>
    <th>Nombre</th>
    <th>Codigo</th>
    <th>Tipo</th>
    <th>Programa</th>
    <th>Creditos</th>
  </tr>
  
  <% @materias.each do |mat| %>

      <tr>
	<td><%= mat.id %></td>
        <td><%= mat.nombre %></td>
        <td><%= mat.codigo %></td>
        <td><%= mat.tipo %></td>
        <td><%= mat.programa %></td>
	<td><%= mat.creditos %></td>
      </tr>

  <% end %>
</table>
</div>

app/views/materia/detalles.html.erb
<h1>Detalles Planeación</h1>

<p> <b>Materia:</b> <%= @materia.nombre %> </p>
<p> <b>Código:</b> <%= @materia.codigo %> </p>

<p> Lista de estudiantes para la planeación del semestre <%= @sem %></p>

<div class="well">

<table width=60%;>                         
  <tr>         
                    
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Codigo</th>
    <th>Programa</th>
    <th>Prioridad</th>
  </tr>

<% @reg.each do |r| %>
<% e = Estudiante.find(r.idEstudiante) %>
  <tr>	
    
    <td><%= link_to e.nombre , estudiante_infoestudiante_path(:id => e.id) %></td>
    <td><%= link_to e.apellido , estudiante_infoestudiante_path(:id => e.id) %></td>
    <td><%= link_to e.codigo , estudiante_infoestudiante_path(:id => e.id) %></td>  


    <td><%= e.programa %></td> 


<% if r.prioridad.start_with?('Ultimo') %>
	<td><font color="red"><%= r.prioridad %></font></td> 
<% else %>
<% if r.prioridad.start_with?('Mismo') %>
	<td><font color="green"><%= r.prioridad %></font></td> 
<% else %>
    <td><%= r.prioridad %></td> 
<% end %>
<% end %>
  </tr>
<% end %>
</table> 

</div>

app/views/materia/infomateria.html.erb
<h1>Información de la materia</h1>

<div class="well">


<p><b>Nombre:</b> <%= @mate.nombre %></p>
<p><b>Código materia:</b> <%= @mate.codigo %></p>
<p><b>Programa: </b><%= @mate.programa %></p>
<p><b>Créditos: </b><%= @mate.creditos %></p>


<br>
<p><b>Planeación</b> </p>


<% if(@plan1.first==nil)%>
<% p1=0 %>
<% @p1ulti=0 %>
<% @p1mismo=0 %>
<% else %>
<% p1= @plan1.first.cupos %>
<% end %>

<% if(@plan2.first==nil)%>
<% p2=0 %>
<% @p2ulti=0 %>
<% @p2mismo=0 %>
<% else %>
<% p2=@plan2.first.cupos %>
<% end %>

<% if(@plan3.first==nil)%>
<% p3=0 %>
<% @p3ulti=0 %>
<% @p3mismo=0 %>
<% else %>
<% p3=@plan3.first.cupos %>
<% end %>
 
<% if(@plan4.first==nil)%>
<% p4=0 %>
<% @p4ulti=0 %>
<% @p4mismo=0 %>
<% else %>
<% p4=@plan4.first.cupos %>
<% end %>


<%
bar = LazyHighCharts::HighChart.new('column') do |f|
    f.series(:name=>'Último Semestre',:data=> [ @p1ulti, @p2ulti, @p3ulti, @p4ulti ], :color=>"red")
    f.series(:name=>'Mismo Programa',:data=> [@p1mismo, @p2mismo, @p3mismo, @p4mismo ],:color=>"green")
    f.series(:name=>'Otros',:data=> [p1-@p1ulti-@p1mismo, p2-@p2ulti-@p2mismo, p3-@p3ulti-@p3mismo, p4-@p4ulti-@p4mismo ])
    	
    f.title({ :text=>"Cupos planeados"})

    f.xAxis(:categories=> ["Semstre 1", "Semstre 2", "Semstre 3", "Semstre 4" ])
    f.yAxis(:min=>0,:title=>{ :text=>"Cupos"},:stackLabels=>{ :enabled=>true,:color=>"black"})

    f.options[:chart][:defaultSeriesType] = "column"

    f.plot_options(:series=>{:stacking=>"normal",:dataLabels=>{ :enabled=>true,:color=>"white"}}) 
    f.exporting( :enabled=> false )

   
  end
%>
<%= high_chart("Planeacion", bar) %>



<br>

<p><b>Ver detalles</b> </p>
<% if(@plan1.first==nil)%>
<% else %>
<%= link_to "Semestre 1 " , materia_detalles_path(:id => @mate.id, :sem => "1" ) %>
<% end %>
 - 
<% if(@plan2.first==nil)%>
<% else %>
<%= link_to "Semestre 2 " , materia_detalles_path(:id => @mate.id, :sem => "2" ) %>
<% end %>
 - 
<% if(@plan3.first==nil)%>
<% else %>
<%= link_to "Semestre 3 " , materia_detalles_path(:id => @mate.id, :sem => "3" ) %>
<% end %>
 - 
<% if(@plan4.first==nil)%>
<% else %>
<%= link_to "Semestre 4 " , materia_detalles_path(:id => @mate.id, :sem => "4" ) %>
<% end %>

<% if(@plan1.first==nil and @plan2.first==nil and @plan3.first==nil and @plan4.first==nil  )%>
<p>No se econtraron cupos planeados para esta materia.</p>
<% end %>

</div>

app/views/materia/listafiltrada.html.erb
<h1>MATERIAS</h1>
<br>

<div class="well">

<table width=65%;>                         
  <tr height=40px;>
    <th>id</th>
    <th>Nombre</th>
    <th width=85px;>Código  </th>
    
    <th>Programa</th>
    </tr>
  <% @materias.each do |mat| %>

<% if(@m ==mat.programa) %>
  <tr>
    <td><%= link_to mat.id , materia_infomateria_path(:id => mat.id) %></td> 
    <td><%= link_to mat.nombre , materia_infomateria_path(:id => mat.id) %></td>
    <td><%= link_to mat.codigo , materia_infomateria_path(:id => mat.id) %></td>
    <td><%= mat.programa %></td> 
  </tr>
<% else %>
<% end %>
<% end %>
</table> 


<filtro>
<div class="well" align="center" style="width: 150px; height: 120px">
<p><b>Desea filtrar la lista por:</b></p>
<div align="center" style="position: relative;float: left;">
<%= form_tag(materia_listafiltrada_path , method: "post") do%>
<input name="M" type="hidden" value="MATI">
<%= submit_tag("MATI") %>
<% end %>
</div>
<div align="center" style="position: relative;float: left;">
<%= form_tag(materia_listafiltrada_path , method: "post") do%>
<input name="M" type="hidden" value="MESI">
<%= submit_tag("MESI") %>
<% end %>
</div>
<div align="center" style="position: relative;float: left;">
<%= form_tag(materia_listafiltrada_path , method: "post") do%>
<input name="M" type="hidden" value="MBIT">
<%= submit_tag("MBIT") %>
<% end %>
</div>
<div align="center" style="position: relative;float: left;">
<%= form_tag(materia_listafiltrada_path , method: "post") do%>
<input name="M" type="hidden" value="MISO">
<%= submit_tag("MISO") %>
<% end %>
</div>
<div align="center" style="position: relative;float: left;">
<%= form_tag(materia_new_path , method: "get") do%>
<%= submit_tag("Todos") %>
<% end %>
</div>
</div>
</filtro>

</div>

app/views/materia/new.html.erb
<h1>MATERIAS</h1>
<br>

<div class="well">

<table width=65%;>                         
  <tr height=40px;>
    <th>id</th>
    <th>Nombre</th>
    <th width=85px;>Código  </th>

    <th>Programa</th>
    </tr>
  <% @materias.each do |mat| %>


  <tr>
    <td><%= link_to mat.id , materia_infomateria_path(:id => mat.id) %></td> 
    <td><%= link_to mat.nombre , materia_infomateria_path(:id => mat.id) %></td>
    <td><%= link_to mat.codigo , materia_infomateria_path(:id => mat.id) %></td>
    <td><%= mat.programa %></td> 
  </tr>
<% end %>
</table> 


<filtro>
<div class="well" align="center" style="width: 150px; height: 120px">
<p><b>Desea filtrar la lista por:</b></p>
<div align="center" style="position: relative;float: left;">
<%= form_tag(materia_listafiltrada_path , method: "post") do%>
<input name="M" type="hidden" value="MATI">
<%= submit_tag("MATI") %>
<% end %>
</div>
<div align="center" style="position: relative;float: left;">
<%= form_tag(materia_listafiltrada_path , method: "post") do%>
<input name="M" type="hidden" value="MESI">
<%= submit_tag("MESI") %>
<% end %>
</div>
<div align="center" style="position: relative;float: left;">
<%= form_tag(materia_listafiltrada_path , method: "post") do%>
<input name="M" type="hidden" value="MBIT">
<%= submit_tag("MBIT") %>
<% end %>
</div>
<div align="center" style="position: relative;float: left;">
<%= form_tag(materia_listafiltrada_path , method: "post") do%>
<input name="M" type="hidden" value="MISO">
<%= submit_tag("MISO") %>
<% end %>
</div>
<div align="center" style="position: relative;float: left;">
<%= form_tag(materia_new_path , method: "get") do%>
<%= submit_tag("Todos") %>
<% end %>
</div>
</div>
</filtro>

</div>