config/routes.rb
CoordinadorAlpes::Application.routes.draw do
  get "dashboard/dashboard"
  get "planeacion/resultados"
  get "materia/detalles"
  post "materia/listafiltrada"
  get "materia/infomateria"
  get "estudiante/infoestudiante"
  post "estudiante/listafiltrada"
  get "generar_secciones/generar"
  post "generar_secciones/generarSecciones"

  get "materia/cupos"
  get "estudiante/cuposmas8"
  get "welcome/index"
  get "reservas/ultimosEstudiantes"
  get "reservas/reservasUltimosEst"
  get "reservas/limpiarEscenario"
  get "reservas/home"
  get "reservas/planearSemestres"
  get "reservas/semestrePlaneado"
  get "reservas/detalles"

  get "estudiante/buscarEstudiantesMasOcho"
  post "estudiante/creditosfaltantes"

  get "estado_carpeta/estadoCarpeta"
  get "estado_carpeta/carpeta"
  get "estudiante/result"
  get "materia/new"
  get "estudiante/new"
  get "users/new"

  get "estado_carpeta/home"
  post "estado_carpeta/estadoCarpeta"
  post "reservas/setMateriasSemestre"

  root 'welcome#index'

  

end

app/models/estudiante.rb
class Estudiante < ActiveRecord::Base
end

app/controllers/estudiante_controller.rb
class EstudianteController < ApplicationController
  
def creditosfaltantes
	@codigo= params[:codigo]
	print("\n------codigo---------\n")
	print(@codigo)
	print("\n---------------\n")

	e = Estudiante.find_by codigo:@codigo

	c = Carpeta.where(idEstudiante: e.id , codigoMateria: nil)
	@creditosFestu = c.size*4

	print("\n------creditos---------\n")
	print(@creditosFestu)
	print("\n---------------\n")
  end

  def buscarEstudiantesMasOcho
	@algunos = []
	todos = Estudiante.all
	todos.each do |estudiante|
		id = estudiante.id

		faltantes=Carpeta.select("tipoMateria, sum(creditos) as numCreFaltantes").where("idEstudiante=? AND codigoMateria IS NULL",(id)).group("tipoMateria")
		creditosFal = 0
		faltantes.each do |fal|
			creditosFal += fal.numCreFaltantes		
		end
		
		#creditosFal = (Carpeta.where(idEstudiante: id , idMateria: nil , creditos: 4).size)*4
		if(creditosFal>8)
			e = [ estudiante.id , estudiante.nombre , estudiante.apellido , estudiante.codigo , estudiante.programa , creditosFal ]
			@algunos << e
		end
	end
end

  def result
	@estudiantes = Estudiante.all
  end

  def cuposmas8

    @algunos = []
    todos = Estudiante.all
    todos.each do |estudiante|
      id = estudiante.id

      faltantes=Carpeta.select("tipoMateria, sum(creditos) as numCreFaltantes").where("idEstudiante=? AND codigoMateria IS NULL",(id)).group("tipoMateria")
      creditosFal = 0
      faltantes.each do |fal|
        creditosFal += fal.numCreFaltantes
      end

      #creditosFal = (Carpeta.where(idEstudiante: id , idMateria: nil , creditos: 4).size)*4
      if(creditosFal>8)
        #e = [ estudiante.id , estudiante.nombre , estudiante.apellido , estudiante.codigo , estudiante.programa , creditosFal ]
        #@algunos << e
        i = 0
        faltantes.each do |tipofalt|
          materiasPosibles= Materia.where("tipo=?", tipofalt.tipoMateria)
          if(!materiasPosibles.empty?)
            if(tipofalt.numCreFaltantes<=4)
              #Es solo una materia(Asumiendo materias de 4 créditos)
              if(i<2)
                          randMat=Random.rand(materiasPosibles.length)
                          materia=materiasPosibles[randMat]

                          #materia.cupo+=1
                          #materia.save
                          prioridad=darPrioridad(materia,estudiante)
                          agregarAPlaneacion(materia.id,prioridad,"1",id)


              i += 1
              end
              else
                        #Le faltan dos materias

                        n= (tipofalt.numCreFaltantes/4).round
                        randMat1=Random.rand(materiasPosibles.size)
                        randMat2=Random.rand(materiasPosibles.size)
                        while(randMat1==randMat2)
                          randMat2=Random.rand(materiasPosibles.size)
                         end
              if(i<2)
                          materia=materiasPosibles[randMat1]
                          #materia.cupo+=1
                          #materia.save
                          prioridad=darPrioridad(materia,estudiante)
                          agregarAPlaneacion(materia.id,prioridad,"1",id)
                i += 1
              end
              if(i<2)
                materia=materiasPosibles[randMat2]
                        #materia.cupo+=1
                        #materia.save
                        prioridad=darPrioridad(materia,estudiante)
                        agregarAPlaneacion(materia.id,prioridad,"1",id)
                i += 1
              end
            end
          end
        end
      end
    end
    @materias =  Materia.all

  end

  def agregarAPlaneacion(materia,prioridad,semestre,estudiante)
    planeaciones=Planeacion.all
    planeacionesMateria=planeaciones.where("codigoMateria_id=? AND semestre=1",(materia))
    if(planeacionesMateria.empty?)
      #Toca crearlo
      p=Planeacion.create(idMateria_id: materia, cupos: 1, semestre: semestre)
      Registro.create(idEstudiante_id: estudiante, idPlaneacion_id: p.id, prioridad: prioridad)
    else
      planeado=planeacionesMateria[1]

      Registro.create(idEstudiante_id: estudiante, idPlaneacion_id: 1, prioridad: prioridad)
    end

  end

  def darPrioridad(materia,estudiante)
    prioridad=""
    if(estudiante.programa==materia.programa)
      prioridad="Mismo programa"
    else
      prioridad=estudiante.programa
    end
    return prioridad
  end



def listafiltrada
	@m= params[:M]
	@estudiantes = Estudiante.all
	
  end


def infoestudiante
	id= params[:id]
	@e = Estudiante.find(id)

	#Creditos faltantes
	c = Carpeta.where(idEstudiante: id , codigoMateria: nil)
	@creditosFestu = c.size*4
	#Semestre actual
	#act=40-@creditosFestu
	#tmp=act/8
	#if(tmp<1) 
	tmp=""
	if(@creditosFestu>39)
		tmp ="no ha visto materias"
	end
	#if(tmp==4)
	if(@creditosFestu<9)
		tmp= "Último semestre"
	end
	@semact=tmp
	
	#las materais que le ahcen falta
        @faltantes=Carpeta.select("tipoMateria, sum(creditos) as numCreFaltantes").where("idEstudiante=? AND codigoMateria IS NULL",(@e.id)).group("tipoMateria")
       
    	#tabla planeacion
@s1m1=""
@s1m2=""
@s2m1=""
@s2m2=""
@s3m1=""
@s3m2=""
@s4m1=""
@s4m2=""

	reg = Registro.where(idEstudiante: @e.id )
	reg.each do |re|
		plan = Planeacion.find(re.idPlaneacion)
		seme = plan.semestre
		ma = Materia.find(plan.codigoMateria)
		if(seme == "1")
			if(@s1m1=="")
				@s1m1=ma
			else
				@s1m2=ma
			end
		end
		if(seme =="2")
			if(@s2m1=="")
				@s2m1=ma
			else
				@s2m2=ma
			end
		end
		if(seme =="3")
			if(@s3m1=="")
				@s3m1=ma
			else
				@s3m2=ma
			end
		end
		if(seme =="4")
			if(@s4m1=="")
				@s4m1=ma
			else
				@s4m2=ma
			end
		end
	end      
end



end

app/helpers/estudiante_helper.rb
module EstudianteHelper
end

app/views/estudiante/buscarEstudiantesMasOcho.html.erb
<br><br>
<h1>ESTUDIANTES</h1>
<br>


Estudiantes que NO estan en ultimo semestre
<br><br>
<div class="well">
<table>                         
  <tr>   
    <th>Id</th>      
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Codigo</th>
    <th>Programa</th>
     <th>Creditos</th>	
  </tr>
<% @algunos.each do |estudiante| %>
 <tr>
	 <% estudiante.each do |e| %>
	    <td><%= e %></td>
	<% end %>
 </tr>
<% end %>
</div >

</table> 
<br><br>
<%= form_tag(estudiante_cuposmas8_path , method: "get") do%>
      Darle cupos a todos los estudiantes 
      <%= submit_tag("Dar cupos") %>
<% end %>
<br><br><br><br><br><br>

app/views/estudiante/creditosfaltantes.html.erb
<h1>ESTUDIANTE: </h1>
<br>
<div class="well">
Al estudiante de codigo : <%= @codigo %> Le hacen falta <%= @creditosFestu %> creditos
</div >

app/views/estudiante/cuposmas8.html.erb
<h1>REservas Cupos Estudiantes que NO estan en ultimo semetre</h1>

<br><br>
<div class="well">
<table>
  <tr>
    <th>Nombre</th>
    <th>Tipo</th>
    <th>Cupos</th>
  </tr>
  
  <% @materias.each do |mat| %>

      <tr>
        <td><%= mat.nombre %></td>
        <td><%= mat.tipo %></td>
        <td><%= mat.cupo %></td>
        
      </tr>

  <% end %>
</table>
</div>

app/views/estudiante/infoestudiante.html.erb
<h1>Información del estudiante</h1>


<div class="well">

<p><b>Nombre:</b> <%= @e.nombre %></p>
<p><b>Apellido:</b> <%= @e.apellido %></p>
<p><b>Código:</b> <%= @e.codigo %></p>
<p><b>Programa:</b> <%= @e.programa %></p>

<% if (@semact.==('Último semestre') )%>
	<p >Estudiante de <font color="red"><%= @semact %></font></p>
<% end %>
<% if (@semact.==('no ha visto materias') )%>
	<p >El estudiante no ha visto materias</p>
<% end %>
<br>
<p><b>Tabla Materias faltantes</b></p>
<table width=60%;>
  <tr>
    <th>Tipo de Materia</th>
    <th>Número de Créditos</th>
    <th>Número de Materias</th>

  </tr>
  <% @faltantes.each do |materia| %>

      <tr>
        <td><%= materia.tipoMateria %></td>
        <td><%= materia.numCreFaltantes %></td>
        <td><%= materia.numCreFaltantes/4 %></td>

      </tr>
  <% end %>
</table>
<p>Total creditos faltantes = <%= @creditosFestu %> </p>
<br>

<p><b>Tabla planeación:</b></p>
<table width=60%;>
  <tr>
    <th>Materia \ Semestre</th>
    <th>1</th>
    <th>2</th>
    <th>3</th>
    <th>4</th>
  </tr>
 
      <tr>
        <td bgcolor="#4F81BD"><font color="white"> Materia 1 </font></td>
	<td>
<% if (@s1m1=="")%>
-
<% else %>
<%= link_to @s1m1.codigo , materia_infomateria_path(:id => @s1m1.id) %>
<% end %>
</td>
	<td>
<% if (@s2m1=="")%>
-
<% else %>
<%= link_to @s2m1.codigo , materia_infomateria_path(:id => @s2m1.id) %>
<% end %>
</td>

	<td>
<% if (@s3m1=="")%>
-
<% else %>
<%= link_to @s3m1.codigo , materia_infomateria_path(:id => @s3m1.id) %>
<% end %>
</td>

	<td>
<% if (@s4m1=="")%>
-
<% else %>
<%= link_to @s4m1.codigo , materia_infomateria_path(:id => @s4m1.id) %>
<% end %>
</td>



      </tr>
   <tr>
        <td bgcolor="#4F81BD"><font color="white"> Materia 2 </font></td>
	<td>
<% if (@s1m2=="")%>
-
<% else %>
<%= link_to @s1m2.codigo , materia_infomateria_path(:id => @s1m2.id) %>
<% end %>
</td>
	<td>
<% if (@s2m2=="")%>
-
<% else %>
<%= link_to @s2m2.codigo , materia_infomateria_path(:id => @s2m2.id) %>
<% end %>
</td>

	<td>
<% if (@s3m2=="")%>
-
<% else %>
<%= link_to @s3m2.codigo , materia_infomateria_path(:id => @s3m2.id) %>
<% end %>
</td>

	<td>
<% if (@s4m2=="")%>
-
<% else %>
<%= link_to @s4m2.codigo , materia_infomateria_path(:id => @s4m2.id) %>
<% end %>
</td>
      </tr>
</table>


<br><br><br><br>

</div>

app/views/estudiante/listafiltrada.html.erb
<h1>ESTUDIANTES</h1>
<br>

<div class="well">
<table width=60%;>                         
  <tr height=40px;>         
    <th>id</th>                 
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Código</th>
    <th>Programa</th>
  </tr>
<% @estudiantes.each do |estudiante| %>
<% if(@m ==estudiante.programa) %>
  <tr>
    <td><%= link_to estudiante.id , estudiante_infoestudiante_path(:id => estudiante.id) %></td> 
    <td><%= link_to estudiante.nombre , estudiante_infoestudiante_path(:id => estudiante.id) %></td>
    <td><%= link_to estudiante.apellido , estudiante_infoestudiante_path(:id => estudiante.id) %></td>
    <td><%= link_to estudiante.codigo , estudiante_infoestudiante_path(:id => estudiante.id) %></td>  
    <td><%= estudiante.programa %></td> 
  </tr>
<% else %>
<% end %>
<% end %>
</table> 


<filtro>
<div class="well" align="center" style="width: 150px; height: 120px">
<p><b>Desea filtrar la lista por:</b></p>
<div align="center" style="position: relative;float: left;">
<%= form_tag(estudiante_listafiltrada_path , method: "post") do%>
<input name="M" type="hidden" value="MATI">
<%= submit_tag("MATI") %>
<% end %>
</div>
<div align="center" style="position: relative;float: left;">
<%= form_tag(estudiante_listafiltrada_path , method: "post") do%>
<input name="M" type="hidden" value="MESI">
<%= submit_tag("MESI") %>
<% end %>
</div>
<div align="center" style="position: relative;float: left;">
<%= form_tag(estudiante_listafiltrada_path , method: "post") do%>
<input name="M" type="hidden" value="MBIT">
<%= submit_tag("MBIT") %>
<% end %>
</div>
<div align="center" style="position: relative;float: left;">
<%= form_tag(estudiante_listafiltrada_path , method: "post") do%>
<input name="M" type="hidden" value="MISO">
<%= submit_tag("MISO") %>
<% end %>
</div>
<div align="center" style="position: relative;float: left;">
<%= form_tag(estudiante_result_path , method: "get") do%>
<%= submit_tag("Todos") %>
<% end %>
</div>
</div>
</filtro>

</div>

app/views/estudiante/new.html.erb
<h1>Estudiante#new</h1>
<p>Find me in app/views/estudiante/new.html.erb</p>

<br>
<%= form_tag(estudiante_result_path , method: "get") do%>
    <p> mostrar todos los estudiantes</p>
<%= submit_tag("mostrar") %>
<% end %>

<br><br><br><br>

<%= form_tag(estudiante_creditosfaltantes_path , method: "post") do%>
<p> Conocer creditos faltantes del estudiante :</p>
  <br> 
<p> Codigo estudiante :</p>
<input name="codigo">
<%= submit_tag("consultar") %>
<% end %>

<%= form_tag(estudiante_buscarEstudiantesMasOcho_path , method: "get") do%>
<p> A los estudiantes de mas de 8 creditos asigarles aleatoriamente cupos en las materias del tipo que le faltan</p>
  <br> 
<%= submit_tag("Ver") %>
<% end %>

app/views/estudiante/result.html.erb
<h1>ESTUDIANTES</h1>
<br>

<div class="well">

<table width=60%;>                         
  <tr height=40px;>         
    <th>id</th>                 
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Código</th>
    <th>Programa</th>
  </tr>
<% @estudiantes.each do |estudiante| %>
  <tr>
    <td><%= link_to estudiante.id , estudiante_infoestudiante_path(:id => estudiante.id) %></td> 
    <td><%= link_to estudiante.nombre , estudiante_infoestudiante_path(:id => estudiante.id) %></td>
    <td><%= link_to estudiante.apellido , estudiante_infoestudiante_path(:id => estudiante.id) %></td>
    <td><%= link_to estudiante.codigo , estudiante_infoestudiante_path(:id => estudiante.id) %></td>  
    <td><%= estudiante.programa %></td> 
  </tr>
<% end %>
</table> 


<filtro>
<div class="well" align="center" style="width: 150px; height: 120px">
<p><b>Desea filtrar la lista por:</b></p>
<div align="center" style="position: relative;float: left;">
<%= form_tag(estudiante_listafiltrada_path , method: "post") do%>
<input name="M" type="hidden" value="MATI">
<%= submit_tag("MATI") %>
<% end %>
</div>
<div align="center" style="position: relative;float: left;">
<%= form_tag(estudiante_listafiltrada_path , method: "post") do%>
<input name="M" type="hidden" value="MESI">
<%= submit_tag("MESI") %>
<% end %>
</div>
<div align="center" style="position: relative;float: left;">
<%= form_tag(estudiante_listafiltrada_path , method: "post") do%>
<input name="M" type="hidden" value="MBIT">
<%= submit_tag("MBIT") %>
<% end %>
</div>
<div align="center" style="position: relative;float: left;">
<%= form_tag(estudiante_listafiltrada_path , method: "post") do%>
<input name="M" type="hidden" value="MISO">
<%= submit_tag("MISO") %>
<% end %>
</div>
<div align="center" style="position: relative;float: left;">
<%= form_tag(estudiante_result_path , method: "get") do%>
<%= submit_tag("Todos") %>
<% end %>
</div>
</div>
</filtro>

</div>