config/routes.rb
CoordinadorAlpes::Application.routes.draw do
  get "dashboard/dashboard"
  get "planeacion/resultados"
  get "materia/detalles"
  post "materia/listafiltrada"
  get "materia/infomateria"
  get "estudiante/infoestudiante"
  post "estudiante/listafiltrada"
  get "generar_secciones/generar"
  post "generar_secciones/generarSecciones"

  get "materia/cupos"
  get "estudiante/cuposmas8"
  get "welcome/index"
  get "reservas/ultimosEstudiantes"
  get "reservas/reservasUltimosEst"
  get "reservas/limpiarEscenario"
  get "reservas/home"
  get "reservas/planearSemestres"
  get "reservas/semestrePlaneado"
  get "reservas/detalles"

  get "estudiante/buscarEstudiantesMasOcho"
  post "estudiante/creditosfaltantes"

  get "estado_carpeta/estadoCarpeta"
  get "estado_carpeta/carpeta"
  get "estudiante/result"
  get "materia/new"
  get "estudiante/new"
  get "users/new"

  get "estado_carpeta/home"
  post "estado_carpeta/estadoCarpeta"
  post "reservas/setMateriasSemestre"

  root 'welcome#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.1.1/css/bootstrap.min.css" /> 
  <title>CoordinadorAlpes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<style>	
table, td, th
{
border:1px solid #4F81BD;

}
th
{
background-color:#4F81BD;
color:white;
}
td
{
padding:6px;
}

h1 {
    font-size: 25px;
    line-height: 40px;
}
filtro
{
position:fixed;
left:60%;
top:60%;


}
</style>

</head>




<body>

<div class='container' >
	<div class="logo" align ="center">
  		<%= link_to ( image_tag "logomed.png" ), welcome_index_path %>
	</div>


	<div class="nav" align ="center">

		<div class='navbar-inner'>

			<nav style="font-size:18px;color:#4F81BD">
			<br>
 			 <ul class="navbar pull-center" style="color:#4F81BD">
			  <a href="/materia/new"><u>Materias</u></a> - 
  			  <a href="/estudiante/result?utf8=✓&commit=mostrar"><u>Estudiantes</u></a> - 
  			  <a href="/reservas/detalles"><u>Planeacion</u></a> - 

   			 <a href="/dashboard/dashboard"><u>DashBoard</u></a> 
  			</ul>
			</nav>

		</div>
	</div>


	<div class="container-fluid" >
  		 <div class="row-fluid">
			<div class="well" style="color:#4F81BD">
   			 <%= yield %>
	 		</div>
		</div>
	</div>

	
	<div class="well" style="color:#4F81BD">
   			 <p align ="center">By : Lucas Latorre, Sebastian Eraso , Andrea Buitrago , Viviana Salcedo<p>
	 </div>
	<br><br>
</div>

</body>

</html>